{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import List\n",
    "\n",
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from dash.dependencies import Input, Output\n",
    "import dash_table\n",
    "\n",
    "import plotly.graph_objs as go\n",
    "import plotly.plotly as py\n",
    "import plotly.figure_factory as ff\n",
    "\n",
    "from flask_cors import CORS\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "import os\n",
    "import requests\n",
    "import io"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "url='https://raw.githubusercontent.com/dkremlg/Booking-Curves/master/GUI_in.csv'\n",
    "s=requests.get(url).content\n",
    "df=pd.read_csv(io.StringIO(s.decode('utf-8')),sep=',')\n",
    "\n",
    "df['Dprio']=df['Dprio'].astype('float')\n",
    "df['NumPax']=df['NumPax'].astype('float')\n",
    "df['Ideal_lower']=df['Ideal_lower'].astype('float')\n",
    "df['Ideal_average_downweighted']=df['Ideal_average_downweighted'].astype('float')\n",
    "df['Ideal_average_full']=df['Ideal_average_full'].astype('float')\n",
    "df['Ideal_upper']=df['Ideal_upper'].astype('float')\n",
    "\n",
    "dep_dates = df['DepDate'].unique()\n",
    "dtime = df['dtime'].unique()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Function for conditional coloring"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "COLORS = [\n",
    "    {\n",
    "        'background': '#FF0000',\n",
    "        'text': 'black'\n",
    "    },\n",
    "    {\n",
    "        'background': '#5DFC0A',\n",
    "        'text': 'black'\n",
    "    },\n",
    "]\n",
    "\n",
    "def cell_style(value1, value2, value3):\n",
    "\n",
    "    # style = {}\n",
    "    relative_value1 = value1 - value2\n",
    "    relative_value2 = value1 - value3\n",
    "\n",
    "    if relative_value1 < 0 or relative_value2 > 0:\n",
    "            style = {\n",
    "                'backgroundColor': COLORS[0]['background'],\n",
    "                'color': COLORS[0]['text']\n",
    "            }\n",
    "    else:\n",
    "            style = {\n",
    "                'backgroundColor': COLORS[1]['background'],\n",
    "                'color': COLORS[1]['text']\n",
    "            }\n",
    "    return style"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Function for table creation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_table(dataframe, max_rows=50):\n",
    "    rows = []\n",
    "    for i in range(min(len(dataframe), max_rows)):\n",
    "        row = []\n",
    "        for col in dataframe.columns:\n",
    "            if col == 'NumPax':\n",
    "                value1 = dataframe.iloc[i][col]\n",
    "                value2 = dataframe.iloc[i]['Ideal_lower']\n",
    "                value3 = dataframe.iloc[i]['Ideal_upper']\n",
    "                style = cell_style(value1, value2, value3)\n",
    "                row.append(html.Td(value1, style=style))\n",
    "            else:\n",
    "                value = dataframe.iloc[i][col]\n",
    "                row.append(html.Td(value))\n",
    "        rows.append(html.Tr(row))\n",
    "\n",
    "    return html.Table(\n",
    "            # Header\n",
    "            [html.Tr([html.Th(col) for col in dataframe.columns])] +\n",
    "\n",
    "            # Body\n",
    "            rows)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Import external stylesheet"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Core code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: Do not use the development server in a production environment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [08/Apr/2019 10:56:25] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2019 10:56:25] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2019 10:56:25] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "[2019-04-08 10:56:25,707] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-9-66404ba296cf>\", line 25, in update_table\n",
      "    dff = df[(df['DepDate'] == value_depdates)&(df['DepDate'] == value_dtime)] # update with your own logic\n",
      "NameError: name 'value_depdates' is not defined\n",
      "127.0.0.1 - - [08/Apr/2019 10:56:25] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-08 10:56:28,463] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-9-66404ba296cf>\", line 25, in update_table\n",
      "    dff = df[(df['DepDate'] == value_depdates)&(df['DepDate'] == value_dtime)] # update with your own logic\n",
      "NameError: name 'value_depdates' is not defined\n",
      "127.0.0.1 - - [08/Apr/2019 10:56:28] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-08 10:56:30,277] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-9-66404ba296cf>\", line 25, in update_table\n",
      "    dff = df[(df['DepDate'] == value_depdates)&(df['DepDate'] == value_dtime)] # update with your own logic\n",
      "NameError: name 'value_depdates' is not defined\n",
      "127.0.0.1 - - [08/Apr/2019 10:56:30] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-08 10:56:33,653] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-9-66404ba296cf>\", line 25, in update_table\n",
      "    dff = df[(df['DepDate'] == value_depdates)&(df['DepDate'] == value_dtime)] # update with your own logic\n",
      "NameError: name 'value_depdates' is not defined\n",
      "127.0.0.1 - - [08/Apr/2019 10:56:33] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-08 10:56:35,141] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-9-66404ba296cf>\", line 25, in update_table\n",
      "    dff = df[(df['DepDate'] == value_depdates)&(df['DepDate'] == value_dtime)] # update with your own logic\n",
      "NameError: name 'value_depdates' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [08/Apr/2019 10:56:35] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-08 10:56:38,263] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-9-66404ba296cf>\", line 25, in update_table\n",
      "    dff = df[(df['DepDate'] == value_depdates)&(df['DepDate'] == value_dtime)] # update with your own logic\n",
      "NameError: name 'value_depdates' is not defined\n",
      "127.0.0.1 - - [08/Apr/2019 10:56:38] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-08 10:57:00,326] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\dkoch\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-9-66404ba296cf>\", line 25, in update_table\n",
      "    dff = df[(df['DepDate'] == value_depdates)&(df['DepDate'] == value_dtime)] # update with your own logic\n",
      "NameError: name 'value_depdates' is not defined\n",
      "127.0.0.1 - - [08/Apr/2019 10:57:00] \"POST /_dash-update-component HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "app = dash.Dash(__name__, external_stylesheets=external_stylesheets)\n",
    "\n",
    "app.layout = html.Div(children=[\n",
    "    # Header\n",
    "    html.H4(children='Booking curve steering system'),\n",
    "    # Dropdown for departure dates\n",
    "    dcc.Dropdown(id = 'dropdown_depdates',\n",
    "    options=[{\n",
    "    'label': i,\n",
    "    'value': i\n",
    "    } for i in dep_dates],\n",
    "    value='All Departure Dates'),\n",
    "    # Dropdown for departure times\n",
    "    dcc.Dropdown(id = 'dropdown_dtime',\n",
    "    options=[{\n",
    "    'label': i,\n",
    "    'value': i\n",
    "    } for i in dtime],\n",
    "    value='All Departure Times'),    \n",
    "    html.Div(id='table-container'),\n",
    "])\n",
    "\n",
    "@app.callback(Output('table-container', 'children'), [Input('dropdown_depdates', 'value'), Input('dropdown_dtime', 'value')])\n",
    "def update_table(value_depdate, value_dtime):\n",
    "    dff = df[(df['DepDate'] == value_depdates)&(df['DepDate'] == value_dtime)] # update with your own logic\n",
    "    return generate_table(dff)\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
